Homework 3
Otus-DevOps-2018-05/egor-a-p_infra pull request #2
Opened 2018-06-19 11:52 UTC by egor-a-p

# Выполнено ДЗ №3

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - задание с 35 слайда про подключение через бастион хост
 - остальные пункты

## Как запустить проект:
 - проект пока не запускается

## Как проверить работоспособность:
 - выполнить комманды/подключится по vpn

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2018-06-26 19:10 UTC, chromko requested changes
Привет!

Поправь, пожалуйста скрипт;
 В остальном ок - зачту после исправления.

2018-06-26 19:10 UTC, chromko commented on setupvpn.sh
> +cat <<EOF> setupvpn.sh
Странновато выглядит - не находишь ? =)
В самом скрипте cat уже не должно быть

2018-06-26 19:10 UTC, chromko commented on README.md
> +### Подключение по алиасу someinternalhost
Хорошее рабочее решение, мне нравится)

2018-06-27 10:24 UTC, egor-a-p commented
Исправился - копипаста видимо, бес попутал.

2018-06-29 06:59 UTC, chromko approved these changes
Все ок.

2018-06-29 07:47 UTC, merged